DELETE FROM `world`.`command` WHERE  `name`='migration';
DELETE FROM `world`.`command` WHERE  `name`='diamond';
DELETE FROM `world`.`command` WHERE  `name`='diamond level';
DELETE FROM `world`.`command` WHERE  `name`='diamond guild';
DELETE FROM `world`.`command` WHERE  `name`='diamond guild level';
DELETE FROM `world`.`command` WHERE  `name`='diamond deserteur';
DELETE FROM `world`.`command` WHERE  `name`='diamond guild rename';
UPDATE `world`.`command` SET `help`='Syntax: .spectate player in PvP arena' WHERE  `name`='spectate';
SELECT `name`, `security`, `help` FROM `world`.`command` WHERE  `name`='spectate';
UPDATE `world`.`command` SET `help`='Syntax: .spectate player in PvP arena' WHERE  `name`='spectator';
SELECT `name`, `security`, `help` FROM `world`.`command` WHERE  `name`='spectator';
UPDATE `world`.`command` SET `help`='Syntax: .spectator leave > Leave arena' WHERE  `name`='spectator leave';
SELECT `name`, `security`, `help` FROM `world`.`command` WHERE  `name`='spectator leave';
UPDATE `world`.`command` SET `help`='Syntax: .spectator watch player' WHERE  `name`='spectator watch';
SELECT `name`, `security`, `help` FROM `world`.`command` WHERE  `name`='spectator watch';
DELETE FROM `world`.`command` WHERE  `name`='synchronized';DELETE FROM `world`.`creature_addon` WHERE  `guid`= 116999;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 117074;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 117211;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 117244;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57894;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154568;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154566;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154564;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154560;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154555;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154549;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154548;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154547;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154546;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154521;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154522;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154524;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154525;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154526;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154531;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154533;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154536;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154537;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154539;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154544;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149520;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149522;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149524;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149527;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57965;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57993;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58054;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58067;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58080;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58092;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58152;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58157;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58160;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58287;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58339;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58356;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58394;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58520;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154174;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 150015;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58565;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 105155;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 51900;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 52028;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 52392;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 52430;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 53027;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 6994;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 113739;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154598;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154593;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154582;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154552;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 15036410;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 15036409;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 15036441;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56546;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56551;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56565;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56595;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56615;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56626;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56645;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56714;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56715;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56718;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56727;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56734;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56735;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56746;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56751;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56783;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56784;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56867;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56907;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56931;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56942;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56946;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56950;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56958;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56962;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57023;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57089;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57153;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57163;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57165;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57247;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57274;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57288;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57300;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57329;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57350;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57355;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57404;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57444;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 32287;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57511;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57602;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57634;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57682;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57694;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57716;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57736;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268668;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268665;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268559;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268648;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268649;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 32264;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 32848;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 1449;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 72880;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 71077;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 70830;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 70791;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91599;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91576;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91536;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91483;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91481;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91340;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91338;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91277;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91212;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91176;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91160;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91153;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91097;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91083;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91061;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91043;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90921;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90891;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90872;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90868;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90846;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90775;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90718;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90637;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90601;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90547;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90508;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90463;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90372;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90319;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90311;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90286;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90284;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90201;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90193;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87806;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87764;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87762;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87721;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87712;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87705;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87673;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87665;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87613;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87607;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87566;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87539;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87501;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87441;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87406;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87399;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87385;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87330;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87276;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87180;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87119;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87061;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86957;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86921;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86910;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86794;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86793;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86774;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86719;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 125521;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126370;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126381;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126642;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126796;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 109346;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 109764;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 110106;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350136;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350135;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350134;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350133;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350132;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350131;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350130;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 175530;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 175532;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 176116;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 176117;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 178154;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 163215;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162708;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162707;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162704;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162705;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162706;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162659;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 6661;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 6663;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69264;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69268;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127628;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99915;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69272;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69266;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99911;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99919;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 320132;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99918;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99910;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 76753;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99917;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99909;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 161944;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 161939;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 138024;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127483;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127484;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127485;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127481;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127482;/* Alliance 1v1 queue / spectator */
DELETE FROM `world`.`creature` WHERE  `guid`=1013166; 
DELETE FROM `world`.`creature` WHERE  `guid`=1013164;
/* Horde 1v1 queue / spectator */
DELETE FROM `world`.`creature` WHERE  `guid`=1013165;
DELETE FROM `world`.`creature` WHERE  `guid`=1013167;
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `comment`) VALUES ('2', '974', 'Darkmoon Faire - Area Disabled');INSERT INTO `world`.`disables` (`sourceType`, `entry`, `comment`) VALUES ('2', '876', 'GM Island - Area Disabled'); /* Fixes startup issue */
DELETE FROM `gossip_menu` WHERE (`Entry`=15086 AND `Text_Id`=21408) OR (`Entry`=20913 AND `Text_Id`=31474);
DELETE FROM `npc_text` WHERE `ID` IN (27896);
INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `BroadcastTextID0`, `lang0`, `Prob0`, `em0_0`, `em0_1`, `em0_2`, `em0_3`, `em0_4`, `em0_5`) VALUES
(27896,"I'm very sorry, but I no longer have relics to sell you. Their magic seems to have extinguished! Perhaps I'll go into dancing full time now, it would be a nice change of pace.","",68132,0,1,0,0,0,0,0,0);
/* Flowers in front of Stormwind Auction House removed */
DELETE FROM `world`.`gameobject` WHERE  `guid`=11229130;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11229129;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11229124;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11229123;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11229049;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11229121;
/* GM Island cleanup */
DELETE FROM `world`.`gameobject` WHERE  `guid`=43452;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11242868;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11228898;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11228888;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11228773;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11228755;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11228739;
DELETE FROM `world`.`gameobject` WHERE  `guid`=11228713;-- 
DELETE FROM `conditions` WHERE `SourceEntry` IN (36460) AND `SourceTypeOrReferenceId`=13;
INSERT INTO conditions (SourceTypeOrReferenceId, SourceGroup, SourceEntry, SourceId, ElseGroup, ConditionTypeOrReference, ConditionTarget, ConditionValue1, ConditionValue2, ConditionValue3, NegativeCondition, ErrorType, ErrorTextId, ScriptName, COMMENT) VALUES 
(13, 4, 36460, 0, 0, 31, 0, 3, 21262, 0, 0, 0, 0, "", "");

SET @ENTRY := 21262;
UPDATE `creature_template` SET `AIName`='SmartAI', `flags_extra`=130 WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@ENTRY) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,8,0,100,0,36460,0,5000,5000,11,34815,0,0,0,0,0,1,0,0,0,0,0,0,0,"Equipement trigger - On Spellhit - Cast spell"),
(@ENTRY,0,1,2,61,0,100,0,0,0,0,0,41,0,0,0,0,0,0,20,183808,5,0,0,0,0,0,"Equipement trigger - On Spellhit - despawn gob"),
(@ENTRY,0,2,3,61,0,100,0,0,0,0,0,41,0,0,0,0,0,0,20,183807,5,0,0,0,0,0,"Equipement trigger - On Spellhit - despawn gob"),
(@ENTRY,0,3,4,61,0,100,0,0,0,0,0,41,0,0,0,0,0,0,20,183806,5,0,0,0,0,0,"Equipement trigger - On Spellhit - despawn gob"),
(@ENTRY,0,4,0,61,0,100,0,0,0,0,0,41,0,0,0,0,0,0,20,183805,5,0,0,0,0,0,"Equipement trigger - On Spellhit - despawn gob");

DELETE FROM `disables` WHERE `sourceType`=0 AND `entry` IN (36460);
INSERT INTO `disables`(`sourceType`,`entry`,`flags`,`comment`) VALUES
(0,36460,64,'Ignore LOS');
-- Knucklerot SAI
SET @ENTRY := 16246;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,3000,6000,8000,13000,11,3396,32,0,0,0,0,5,0,0,0,0,0,0,0,"Knucklerot - In Combat - Cast 'Corrosive Poison'"),
(@ENTRY,0,1,0,9,0,100,0,0,5,5000,9000,11,8014,1,0,0,0,0,5,0,0,0,0,0,0,0,"Knucklerot - Within 0-5 Range - Cast 'Tetanus'");

-- Luzran SAI
SET @ENTRY := 16245;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,9,0,100,0,0,5,7000,11000,11,13444,0,0,0,0,0,2,0,0,0,0,0,0,0,"Luzran - Within 0-5 Range - Cast 'Sunder Armor'"),
(@ENTRY,0,1,0,0,0,100,0,12000,15000,13000,17000,11,40504,1,0,0,0,0,2,0,0,0,0,0,0,0,"Luzran - In Combat - Cast 'Cleave'"),
(@ENTRY,0,2,0,0,0,100,0,9000,12000,15000,21000,11,31389,1,0,0,0,0,2,0,0,0,0,0,0,0,"Luzran - In Combat - Cast 'Knock Away'");

-- Npc spawned in WDB :)UPDATE `world`.`creature_template` SET `name`='Solo Queue', `subname`='Valhalla Servers' WHERE  `entry`=123456;
SELECT `entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified` FROM `world`.`creature_template` WHERE  `entry`=123456;


UPDATE `world`.`creature_template` SET `modelid1`='23838' WHERE  `entry`=123456;
SELECT `entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified` FROM `world`.`creature_template` WHERE  `entry`=123456;UPDATE `world`.`creature_template` SET `name`='Arena Spectator', `subname`='Valhalla Servers' WHERE  `entry`=1758;
SELECT `entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified` FROM `world`.`creature_template` WHERE  `entry`=1758;


UPDATE `world`.`creature_template` SET `modelid1`='1280' WHERE  `entry`=1758;
SELECT `entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified` FROM `world`.`creature_template` WHERE  `entry`=1758;/* Corrupt research_sites cleanup */
DELETE FROM `world`.`research_sites` WHERE  `id`=167 AND `entry`=483 AND `map`=0 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`='' LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=12 AND `entry`=24 AND `map`=0 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C6573206465206C20617574656C206465205A756C LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=16 AND `entry`=140 AND `map`=0 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x4D4F44C3884C452054524F4C4C LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=17 AND `entry`=142 AND `map`=0 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x4D4F44C3884C45204E41494E LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=23 AND `entry`=161 AND `map`=0 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x4D4F44C3884C4520454C4645204445204C41204E554954 LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=92 AND `entry`=323 AND `map`=1 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x4372C3AA746520646520666F7373696C65732064657320436F676E6564756E6573 LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=108 AND `entry`=355 AND `map`=530 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C657320646573207275696E65732041726B6C6F6E LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=111 AND `entry`=363 AND `map`=530 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C657320647520706F73746520646520426572636561752D64652D6C20C38974C3A9 LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=123 AND `entry`=387 AND `map`=530 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C6573206465206C612068616C746520646520476C697373656E7461696C6C65 LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=127 AND `entry`=399 AND `map`=530 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x466F727465726573736520477565756C652D64652D647261676F6E LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=139 AND `entry`=423 AND `map`=571 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C657320646573207275696E65732064657320436F757263696E676C616E7473 LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=152 AND `entry`=451 AND `map`=571 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C657320646520466CC3A961756C6D65 LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=159 AND `entry`=467 AND `map`=1 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C65732064752073616E63747561697265206465204D616C6F726E65 LIMIT 1;
DELETE FROM `world`.`research_sites` WHERE  `id`=161 AND `entry`=471 AND `map`=0 AND `minSkill`=0 AND `minLevel`=0 AND `position_x`=0 AND `position_y`=0 AND `position_z`=0 AND `enable`=2 AND `comment`=0x5369746520646520666F75696C6C657320646573206A617264696E73206465205175656C20446F726D6972 LIMIT 1;

/* creature_addon` trash cleanup */
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 116999;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 117074;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 117211;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 117244;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57894;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154568;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154566;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154564;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154560;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154555;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154549;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154548;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154547;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154546;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154521;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154522;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154524;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154525;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154526;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154531;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154533;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154536;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154537;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154539;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154544;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149520;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149522;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149524;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 149527;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57965;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57993;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58054;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58067;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58080;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58092;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58152;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58157;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58160;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58287;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58339;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58356;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58394;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58520;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154174;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 150015;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 58565;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 105155;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 51900;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 52028;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 52392;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 52430;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 53027;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 6994;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 113739;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154598;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154593;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154582;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 154552;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 15036410;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 15036409;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 15036441;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56546;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56551;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56565;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56595;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56615;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56626;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56645;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56714;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56715;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56718;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56727;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56734;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56735;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56746;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56751;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56783;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56784;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56867;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56907;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56931;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56942;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56946;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56950;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56958;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 56962;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57023;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57089;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57153;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57163;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57165;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57247;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57274;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57288;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57300;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57329;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57350;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57355;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57404;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57444;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 32287;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57511;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57602;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57634;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57682;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57694;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57716;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 57736;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268668;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268665;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268559;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268648;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 268649;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 32264;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 32848;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 1449;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 72880;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 71077;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 70830;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 70791;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91599;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91576;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91536;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91483;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91481;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91340;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91338;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91277;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91212;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91176;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91160;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91153;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91097;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91083;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91061;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 91043;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90921;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90891;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90872;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90868;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90846;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90775;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90718;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90637;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90601;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90547;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90508;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90463;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90372;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90319;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90311;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90286;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90284;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90201;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 90193;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87806;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87764;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87762;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87721;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87712;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87705;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87673;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87665;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87613;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87607;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87566;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87539;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87501;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87441;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87406;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87399;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87385;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87330;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87276;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87180;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87119;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 87061;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86957;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86921;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86910;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86794;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86793;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86774;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 86719;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 125521;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126370;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126381;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126642;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 126796;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 109346;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 109764;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 110106;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350136;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350135;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350134;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350133;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350132;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350131;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 350130;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 175530;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 175532;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 176116;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 176117;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 178154;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 163215;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162708;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162707;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162704;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162705;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162706;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 162659;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 6661;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 6663;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69264;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69268;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127628;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99915;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69272;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 69266;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99911;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99919;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 320132;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99918;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99910;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 76753;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99917;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 99909;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 161944;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 161939;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 138024;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127483;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127484;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127485;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127481;
DELETE FROM `world`.`creature_addon` WHERE  `guid`= 127482;